// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuHQhiKh9BlXB3lnqz89b53OWe08qKCkc',
    appId: '1:348639443380:web:4d23ef5287dbb158485ae1',
    messagingSenderId: '348639443380',
    projectId: 'terhal-legend',
    authDomain: 'terhal-legend.firebaseapp.com',
    storageBucket: 'terhal-legend.appspot.com',
    measurementId: 'G-42M9PHCY15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZT7_XdgeqQyprwSM1PBAixgWUbDDHLc0',
    appId: '1:348639443380:android:d2c5ada89b4b8321485ae1',
    messagingSenderId: '348639443380',
    projectId: 'terhal-legend',
    storageBucket: 'terhal-legend.appspot.com',
  );
}
